<a href="https://colab.research.google.com/github/GlobalFishingWatch/gfw-api-python-client/blob/develop/notebooks/usage-guides/references-data-api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reference Data API

This guide provides detailed instructions on how to use the [gfw-api-python-client](https://github.com/GlobalFishingWatch/gfw-api-python-client) to access reference data, specifically geographic regions through the Global Fishing Watch [Reference Data API](https://globalfishingwatch.org/our-apis/documentation#regions).

**Note:** See the [Datasets](https://globalfishingwatch.org/our-apis/documentation#api-dataset), [Reference Data Caveats](https://globalfishingwatch.org/our-apis/documentation#reference-data), and [Terms of Use](https://globalfishingwatch.org/our-apis/documentation#terms-of-use) pages in the [GFW API documentation](https://globalfishingwatch.org/our-apis/documentation#introduction) for details on GFW data, API licenses, and rate limits.

## Prerequisites

Before using the `gfw-api-python-client`, ensure it is installed (see the [Getting Started](https://globalfishingwatch.github.io/gfw-api-python-client/getting-started.html) guide) and that you have obtained an API access token from the [Global Fishing Watch API portal](https://globalfishingwatch.org/our-apis/tokens).

## Installation

The `gfw-api-python-client` can be installed easily from either the [Python Package Index (PyPI)](https://pypi.org/project/gfw-api-python-client/) or [Conda](https://anaconda.org/conda-forge/gfw-api-python-client)

In [1]:
# %pip install gfw-api-python-client

In [1]:
# %conda install -c conda-forge gfw-api-python-client

## Usage

Import and use `gfw-api-python-client` in your Python codes

In [2]:
import os

import gfwapiclient as gfw

In [3]:
try:
    from google.colab import userdata

    access_token = userdata.get("GFW_API_ACCESS_TOKEN")
except Exception:
    access_token = os.environ.get("GFW_API_ACCESS_TOKEN")

access_token = access_token or "<PASTE_YOUR_GFW_API_ACCESS_TOKEN_HERE>"

In [4]:
gfw_client = gfw.Client(
    access_token=access_token,
)

**Note:** Use `gfw_client.references` methods to obtain the **Region of Interest (ROI)**, i.e., `region`, which can then be passed directly to the [4Wings API](https://globalfishingwatch.org/our-apis/documentation#map-visualization-4wings-api), [Bulk Download API](https://globalfishingwatch.org/our-apis/documentation#bulk-download-api), [Insights API](https://globalfishingwatch.org/our-apis/documentation#insights-api), and [Events API](https://globalfishingwatch.org/our-apis/documentation#events-api) methods.

## Retrieving Exclusive Economic Zones (EEZs)

In [5]:
eez_regions_result = await gfw_client.references.get_eez_regions()

### Access the list of EEZ region as Pydantic models

In [6]:
eez_regions_data = eez_regions_result.data()

In [7]:
eez_region = eez_regions_data[-1]

In [8]:
eez_region.id, eez_region.dataset, eez_region.label, eez_region.iso3

('8489', 'public-eez-areas', 'Antartic 200NM zone beyond the coastline', 'ATA')

### Access the EEZ regions as a DataFrame

In [9]:
eez_regions_df = eez_regions_result.df()

In [10]:
eez_regions_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 286 entries, 0 to 285
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   dataset      286 non-null    str
 1   id           286 non-null    str
 2   label        286 non-null    str
 3   iso3         235 non-null    str
 4   iso_sov_1    285 non-null    str
 5   iso_sov_2    56 non-null     str
 6   iso_sov_3    6 non-null      str
 7   territory_1  285 non-null    str
dtypes: str(8)
memory usage: 18.0 KB

In [11]:
eez_regions_df[["id", "label", "iso3", "dataset"]].head()

,id,label,iso3,dataset
0,8491,Jordanian Exclusive Economic Zone,JOR,public-eez-areas
1,8467,Uruguayan Exclusive Economic Zone,URY,public-eez-areas
2,5683,Latvian Exclusive Economic Zone,LVA,public-eez-areas
3,48950,Overlapping claim Kuril Islands: Japan / Russia,NaN,public-eez-areas
4,8327,South Korean Exclusive Economic Zone,KOR,public-eez-areas

### Filter the list of EEZ regions to Obtain the Region of Interest (ROI)

In [12]:
eez_rois_result = await gfw_client.references.get_eez_regions(iso3="SEN")

In [13]:
eez_roi = eez_rois_result.data()[0]

In [14]:
eez_roi.id, eez_roi.dataset, eez_roi.label, eez_roi.iso3

('8371', 'public-eez-areas', 'Senegalese Exclusive Economic Zone', 'SEN')

**Note:** Pass `eez_roi` directly to `region` parameter of the [4Wings API](https://globalfishingwatch.org/our-apis/documentation#map-visualization-4wings-api), [Bulk Download API](https://globalfishingwatch.org/our-apis/documentation#bulk-download-api), [Insights API](https://globalfishingwatch.org/our-apis/documentation#insights-api), and [Events API](https://globalfishingwatch.org/our-apis/documentation#events-api) methods.

## Retrieving Marine Protected Areas (MPAs)

In [15]:
mpa_regions_result = await gfw_client.references.get_mpa_regions()

### Access the list of MPA region Pydantic models

In [16]:
mpa_regions_data = mpa_regions_result.data()

In [17]:
mpa_region = mpa_regions_data[-1]

In [18]:
mpa_region.id, mpa_region.dataset, mpa_region.label

('555882474',
 'public-mpa-all',
 'Humedal Tubul Raqui - Santuario de la Naturaleza')

### Access the MPA regions as a DataFrame

In [19]:
mpa_regions_df = mpa_regions_result.df()

In [20]:
mpa_regions_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17172 entries, 0 to 17171
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   dataset  17172 non-null  str
 1   id       17172 non-null  str
 2   label    17172 non-null  str
dtypes: str(3)
memory usage: 402.6 KB

In [21]:
mpa_regions_df.head()

          dataset  id                                              label
0  public-mpa-all   1                      Diamond Reef - Marine Reserve
1  public-mpa-all   2                     Palaster Reef - Marine Reserve
2  public-mpa-all  27                         Folkstone - Marine Reserve
3  public-mpa-all  46  Reserva Biológica Atol Das Rocas - Reserva Bio...
4  public-mpa-all  57            Parque Nacional Do Cabo Orange - Parque

### Filter the list of MPA regions to Obtain the Region of Interest (ROI)

In [22]:
mpa_rois_result = await gfw_client.references.get_mpa_regions(id="555745302")

In [23]:
mpa_roi = mpa_rois_result.data()[0]

In [24]:
mpa_roi.id, mpa_roi.dataset, mpa_roi.label

('555745302', 'public-mpa-all', 'Dorsal de Nasca - Reserva Nacional')

**Note:** Pass `mpa_roi` directly to `region` parameter of the [4Wings API](https://globalfishingwatch.org/our-apis/documentation#map-visualization-4wings-api), [Bulk Download API](https://globalfishingwatch.org/our-apis/documentation#bulk-download-api), [Insights API](https://globalfishingwatch.org/our-apis/documentation#insights-api), and [Events API](https://globalfishingwatch.org/our-apis/documentation#events-api) methods.

## Retrieving Regional Fisheries Management Organizations (RFMOs)

In [25]:
rfmo_regions_result = await gfw_client.references.get_rfmo_regions()

### Access the list of RFMO region as Pydantic models

In [26]:
rfmo_regions_data = rfmo_regions_result.data()

In [27]:
rfmo_region = rfmo_regions_data[-1]

In [28]:
rfmo_region.id, rfmo_region.dataset, rfmo_region.label

('BOBP-IGO', 'public-rfmo', 'BOBP-IGO')

### Access the RFMO regions as a DataFrame

In [29]:
rfmo_regions_df = rfmo_regions_result.df()

In [30]:
rfmo_regions_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   dataset  42 non-null     str
 1   id       42 non-null     str
 2   label    42 non-null     str
 3   id_      42 non-null     str
dtypes: str(4)
memory usage: 1.4 KB

In [31]:
rfmo_regions_df.head()

       dataset       id    label      id_
0  public-rfmo      LTA      LTA      LTA
1  public-rfmo  SEAFDEC  SEAFDEC  SEAFDEC
2  public-rfmo    IATTC    IATTC    IATTC
3  public-rfmo    APFIC    APFIC    APFIC
4  public-rfmo     IPHC     IPHC     IPHC

### Filter the list of RFMO regions to Obtain the Region of Interest (ROI)

In [32]:
rfmo_rois_result = await gfw_client.references.get_rfmo_regions(id="WCPFC")

In [33]:
rfmo_roi = rfmo_rois_result.data()[0]

In [34]:
rfmo_roi.id, rfmo_roi.dataset, rfmo_roi.label

('WCPFC', 'public-rfmo', 'WCPFC')

**Note:** Pass `rfmo_roi` directly to `region` parameter of the [4Wings API](https://globalfishingwatch.org/our-apis/documentation#map-visualization-4wings-api), [Bulk Download API](https://globalfishingwatch.org/our-apis/documentation#bulk-download-api), [Insights API](https://globalfishingwatch.org/our-apis/documentation#insights-api), and [Events API](https://globalfishingwatch.org/our-apis/documentation#events-api) methods.