<a href="https://colab.research.google.com/github/GlobalFishingWatch/gfw-api-python-client/blob/develop/notebooks/getting-started.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Getting Started

This guide introduces you to the basics of using the [gfw-api-python-client](https://github.com/GlobalFishingWatch/gfw-api-python-client).

**Note:** See the [Datasets](https://globalfishingwatch.org/our-apis/documentation#api-dataset), [Data Caveats](https://globalfishingwatch.org/our-apis/documentation#data-caveat), and [Terms of Use](https://globalfishingwatch.org/our-apis/documentation#terms-of-use) pages in the [GFW API documentation](https://globalfishingwatch.org/our-apis/documentation#introduction) for details on GFW data, API licenses, and rate limits.

## Prerequisites

Before using the `gfw-api-python-client`, ensure it is installed (see the [Getting Started](https://globalfishingwatch.github.io/gfw-api-python-client/getting-started.html) guide) and that you have obtained an API access token from the [Global Fishing Watch API portal](https://globalfishingwatch.org/our-apis/tokens).

## Installation

The `gfw-api-python-client` can be easily installed using pip:

In [1]:
# %pip install gfw-api-python-client

## Usage

Import and use `gfw-api-python-client` in your Python codes

In [2]:
import datetime
import os

import gfwapiclient as gfw

In [3]:
try:
    from google.colab import userdata

    access_token = userdata.get("GFW_API_ACCESS_TOKEN")
except Exception:
    access_token = os.environ.get("GFW_API_ACCESS_TOKEN")

access_token = access_token or "<PASTE_YOUR_GFW_API_ACCESS_TOKEN_HERE>"

In [4]:
gfw_client = gfw.Client(
    access_token=access_token,
)

## Making API Requests

### Searching for a Vessel by MMSI

In [5]:
vessel_search_result = await gfw_client.vessels.search_vessels(
    query="412331038",
)

In [6]:
vessel_search_df = vessel_search_result.df()

In [7]:
vessel_search_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   dataset                         5 non-null      str
 1   registry_info_total_records     5 non-null      int64
 2   registry_info                   5 non-null      object
 3   registry_owners                 5 non-null      object
 4   registry_public_authorizations  5 non-null      object
 5   combined_sources_info           5 non-null      object
 6   self_reported_info              5 non-null      object
 7   matchCriteria                   5 non-null      object
dtypes: int64(1), object(6), str(1)
memory usage: 452.0+ bytes

In [8]:
vessel_search_df.head()

,dataset,registry_info_total_records,registry_info,registry_owners,registry_public_authorizations,combined_sources_info,self_reported_info,matchCriteria
0,public-global-vessel-identity:v4.0,0,[],[],[],[{'vessel_id': 'a5ef97d59-9f40-3bdc-e247-daf9c...,[{'id': 'a5ef97d59-9f40-3bdc-e247-daf9c892ceff...,[{'reference': 'a5ef97d59-9f40-3bdc-e247-daf9c...
1,public-global-vessel-identity:v4.0,0,[],[],[],[{'vessel_id': '108c5510b-b6aa-9cf2-8b86-0598d...,[{'id': '108c5510b-b6aa-9cf2-8b86-0598de546741...,[{'reference': '108c5510b-b6aa-9cf2-8b86-0598d...
2,public-global-vessel-identity:v4.0,1,"[{'id': '4ef90bea19300c6a23f6ce627a80238b', 's...","[{'name': 'ZHOUSHAN SHUNHANG OCEAN FISHERIES',...","[{'date_from': 2017-01-04 00:00:00+00:00, 'dat...",[{'vessel_id': 'da2b09b31-127e-27e0-fe5f-d6d87...,[{'id': '755a48dd4-4bee-4bcf-7b5f-9baea058fc7b...,[{'reference': '755a48dd4-4bee-4bcf-7b5f-9baea...
3,public-global-vessel-identity:v4.0,0,[],[],[],[{'vessel_id': 'd2fbd05f5-57dd-1faa-c384-67a75...,[{'id': 'd2fbd05f5-57dd-1faa-c384-67a75f27fc80...,[{'reference': 'd2fbd05f5-57dd-1faa-c384-67a75...
4,public-global-vessel-identity:v4.0,0,[],[],[],[{'vessel_id': '91df2f8c7-74fd-5b5a-60f5-3d86f...,[{'id': '91df2f8c7-74fd-5b5a-60f5-3d86f9c51ff2...,[{'reference': '91df2f8c7-74fd-5b5a-60f5-3d86f...

#### Get List of Vessel Searched IDs

**Note:** It is recommended to prioritize vessels that include both `registry_info` and `self_reported_info` (AIS), as this indicates a successful match between registry data and AIS information. See how the [Vessels API](https://globalfishingwatch.org/our-apis/documentation#vessels-api) is used in the [Vessel Viewer](https://globalfishingwatch.org/map/) [here](https://globalfishingwatch.org/our-apis/assets/2024_Vessel_Viewer_and_APIs_behind_It.pdf).

In [9]:
vessel_search_ids = vessel_search_result.vessel_ids

In [10]:
vessel_search_ids

['da2b09b31-127e-27e0-fe5f-d6d87e96de6a',
 '755a48dd4-4bee-4bcf-7b5f-9baea058fc7b',
 '3dad49b0b-b2e0-9347-0c4c-e39fea560f9f']

### Getting Details of Vessels Filtered by Vessel Searched IDs

In [11]:
vessels_result = await gfw_client.vessels.get_vessels_by_ids(
    ids=vessel_search_ids,
)

In [12]:
vessels_df = vessels_result.df()

In [13]:
vessels_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 7 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   dataset                         1 non-null      str
 1   registry_info_total_records     1 non-null      int64
 2   registry_info                   1 non-null      object
 3   registry_owners                 1 non-null      object
 4   registry_public_authorizations  1 non-null      object
 5   combined_sources_info           1 non-null      object
 6   self_reported_info              1 non-null      object
dtypes: int64(1), object(5), str(1)
memory usage: 188.0+ bytes

In [14]:
vessels_df.head()

,dataset,registry_info_total_records,registry_info,registry_owners,registry_public_authorizations,combined_sources_info,self_reported_info
0,public-global-vessel-identity:v4.0,3,"[{'id': '4ef90bea19300c6a23f6ce627a80238b', 's...","[{'name': 'ZHOUSHAN SHUNHANG OCEAN FISHERIES',...","[{'date_from': 2017-01-04 00:00:00+00:00, 'dat...",[{'vessel_id': 'da2b09b31-127e-27e0-fe5f-d6d87...,[{'id': '755a48dd4-4bee-4bcf-7b5f-9baea058fc7b...

#### Get List of Vessel IDs

**Note:** It is recommended to prioritize vessels that include both `registry_info` and `self_reported_info` (AIS), as this indicates a successful match between registry data and AIS information. See how the [Vessels API](https://globalfishingwatch.org/our-apis/documentation#vessels-api) is used in the [Vessel Viewer](https://globalfishingwatch.org/map/) [here](https://globalfishingwatch.org/our-apis/assets/2024_Vessel_Viewer_and_APIs_behind_It.pdf).

In [15]:
vessel_ids = vessels_result.vessel_ids

In [16]:
vessel_ids

['da2b09b31-127e-27e0-fe5f-d6d87e96de6a',
 '755a48dd4-4bee-4bcf-7b5f-9baea058fc7b',
 '3dad49b0b-b2e0-9347-0c4c-e39fea560f9f']

### Getting Insights Related to Fishing Events for the Vessel Searched

In [17]:
start_date = min(vessels_result.transmission_dates_from)

In [18]:
start_date

datetime.date(2013, 11, 15)

**Important:** `start_date` must be on or after `January 1, 2020`. [Insights](https://globalfishingwatch.org/our-apis/documentation#insights-api) are available from `January 1, 2020` onwards.

In [19]:
start_date = max(start_date, datetime.date.fromisoformat("2020-01-01"))

In [20]:
end_date = max(vessels_result.transmission_dates_to)

In [21]:
start_date, end_date

(datetime.date(2020, 1, 1), datetime.date(2026, 6, 21))

In [22]:
insights_result = await gfw_client.insights.get_vessel_insights(
    includes=["FISHING"],
    start_date=start_date,
    end_date=end_date,
    vessels=vessel_ids,
)

In [23]:
insights_df = insights_result.df()

In [24]:
insights_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1 entries, 0 to 0
Data columns (total 6 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   period                       1 non-null      object
 1   vessel_ids_without_identity  0 non-null      object
 2   gap                          0 non-null      object
 3   coverage                     0 non-null      object
 4   apparent_fishing             1 non-null      object
 5   vessel_identity              0 non-null      object
dtypes: object(6)
memory usage: 180.0+ bytes

In [25]:
insights_df.head()

,period,vessel_ids_without_identity,gap,coverage,apparent_fishing,vessel_identity
0,"{'start_date': 2020-01-01, 'end_date': 2026-06...",None,None,None,{'datasets': ['public-global-fishing-events:v4...,None

In [26]:
insights_data = insights_result.data()

In [27]:
dict(insights_data.apparent_fishing.period_selected_counters)

{'events': 263,
 'events_gap_off': None,
 'events_in_rfmo_without_known_authorization': 163,
 'events_in_no_take_mpas': 0}

### Getting Fishing Events for the Vessels Searched

In [28]:
events_result = await gfw_client.events.get_all_events(
    datasets=["public-global-fishing-events:latest"],
    start_date=start_date,
    end_date=end_date,
    vessels=vessel_ids,
)

In [29]:
events_df = events_result.df()

In [30]:
events_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 263 entries, 0 to 262
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   start         263 non-null    datetime64[us, UTC]
 1   end           263 non-null    datetime64[us, UTC]
 2   id            263 non-null    str
 3   type          263 non-null    str
 4   position      263 non-null    object
 5   regions       263 non-null    object
 6   bounding_box  263 non-null    object
 7   distances     263 non-null    object
 8   vessel        263 non-null    object
 9   encounter     0 non-null      object
 10  fishing       263 non-null    object
 11  gap           0 non-null      object
 12  loitering     0 non-null      object
 13  port_visit    0 non-null      object
dtypes: datetime64[us, UTC](2), object(10), str(2)
memory usage: 28.9+ KB

In [31]:
events_df.head()

,start,end,id,type,position,regions,bounding_box,distances,vessel,encounter,fishing,gap,loitering,port_visit
0,2020-05-27 12:08:47+00:00,2020-05-27 16:52:19+00:00,a3967b8c86143d60ece964e0d55dd410,fishing,"{'lat': 41.2464, 'lon': 165.0914}","{'mpa': [], 'eez': [], 'rfmo': ['PICES', 'ACAP...","[165.04957333333334, 41.22549333333333, 165.11...","{'start_distance_from_shore_km': 1195.0, 'end_...",{'id': '3dad49b0b-b2e0-9347-0c4c-e39fea560f9f'...,None,"{'total_distance_km': 7.727278367334163, 'aver...",None,None,None
1,2020-05-29 08:23:50+00:00,2020-05-29 08:48:39+00:00,d93fab941578e08fbd0bbcfd6237be5c,fishing,"{'lat': 41.4293, 'lon': 165.5407}","{'mpa': [], 'eez': [], 'rfmo': ['IWC', 'NPAFC'...","[165.53578666666667, 41.42429333333333, 165.54...","{'start_distance_from_shore_km': 1209.0, 'end_...",{'id': '3dad49b0b-b2e0-9347-0c4c-e39fea560f9f'...,None,"{'total_distance_km': 1.6521146705457104, 'ave...",None,None,None
2,2020-11-23 06:45:07+00:00,2020-11-23 07:27:03+00:00,f9a5a8a73b8c43feaea8e2416a4f45dc,fishing,"{'lat': 41.2036, 'lon': 150.862}","{'mpa': [], 'eez': [], 'rfmo': ['NPAFC', 'PICE...","[150.86170666666666, 41.2018016667, 150.862258...","{'start_distance_from_shore_km': 436.0, 'end_d...",{'id': '3dad49b0b-b2e0-9347-0c4c-e39fea560f9f'...,None,"{'total_distance_km': 0.40525710130028725, 'av...",None,None,None
3,2020-11-05 06:39:22+00:00,2020-11-05 12:23:27+00:00,c360eece02f0b6c0a9961da4f9d14338,fishing,"{'lat': 43.8173, 'lon': 154.7858}","{'mpa': [], 'eez': [], 'rfmo': ['WCPFC', 'IWC'...","[154.78373333333334, 43.8052266667, 154.797158...","{'start_distance_from_shore_km': 404.0, 'end_d...",{'id': '3dad49b0b-b2e0-9347-0c4c-e39fea560f9f'...,None,"{'total_distance_km': 2.763389184389981, 'aver...",None,None,None
4,2020-11-22 11:02:58+00:00,2020-11-22 20:54:28+00:00,7bf028bb91043ebc9c76def4184c9839,fishing,"{'lat': 41.2789, 'lon': 150.7685}","{'mpa': [], 'eez': [], 'rfmo': ['NPFC', 'IWC',...","[150.72186666666667, 41.271973333333335, 150.8...","{'start_distance_from_shore_km': 422.0, 'end_d...",{'id': '3dad49b0b-b2e0-9347-0c4c-e39fea560f9f'...,None,"{'total_distance_km': 10.085051379476868, 'ave...",None,None,None